name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
        scala: [2.11.x, 2.12.x, 2.13.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: sbt
      - name: Test
        run: sbt ++${{matrix.scala}} test versionPolicyCheck package
